apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    cluster: spin-deck
  name: spin-deck-loadbalancer
  namespace: spinnaker
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: spin
    cluster: spin-deck
  sessionAffinity: None
  type: LoadBalancer
